[package]
name = "merkle-heapless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
mmr-macro = {path = "./mmr-macro"}

[features]
mmr_macro = []